version: '3.9'
services:
  consul-seed:
    image: consul:latest
    ports:
      - "8301:8300"
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: "agent -server -ui -bootstrap-expect=3 -log-level=debug -disable-host-node-id -client=0.0.0.0 -retry-join=consul-seed:8301 -retry-join=consul-cluster:8300"
    deploy:
      placement:
        constraints: [node.role == manager]

  consul-cluster:
    image: consul:latest
    ports:
      - "8300:8300"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    depends_on:
      - consul-seed
    command: "agent -server -log-level=debug -disable-host-node-id -client=0.0.0.0 -retry-join=consul-seed:8301 -retry-join=consul-cluster:8300"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]

  consul-agents:
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: "agent -disable-host-node-id -retry-join=consul-seed:8301 -log-level=debug -client=0.0.0.0 -retry-join=consul-cluster:8300"
    depends_on:
      - consul-seed
    deploy:
      replicas: 3

  employee:
    image: sysout1kk/api-employee
    environment:
      - spring.cloud.consul.host=consul-agents
    depends_on:
      - consul-agents
    deploy:
      replicas: 3

  company:
    image: sysout1kk/api-company
    ports:
      - "8080:8090"
    environment:
      - spring.cloud.consul.host=consul-agents
      - logging.level.org.springframework.web.client.RestTemplate=DEBUG
      - logging.level.org.springframework.cloud.consul=DEBUG
    depends_on:
      - consul-agents
    deploy:
      replicas: 3

networks:
  default:
    external:
      name: backend
