version: '3.9'
services:
  consul-seed:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: "agent -server -ui -bootstrap-expect=3 -disable-host-node-id -client=0.0.0.0 -retry-join=consul-cluster -retry-join=consul-seed"
    deploy:
      placement:
        constraints: [node.role == manager]

  consul-cluster:
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: eth0
    depends_on:
      - consul-seed
    command: "agent -server -ui -disable-host-node-id -client=0.0.0.0 -retry-join=consul-seed -retry-join=consul-cluster"
    deploy:
      replicas: 2

  consul-agents:
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: "agent -disable-host-node-id -retry-join=consul-seed -client=0.0.0.0 -retry-join=consul-cluster"
    depends_on:
      - consul-seed
    deploy:
      replicas: 3

  api-employee:
    image: sysout1kk/api-employee
    ports:
      - "8081:8091"
    environment:
      - spring.cloud.consul.host=consul-agents
    depends_on:
      - consul-agents
    deploy:
      replicas: 3

  api-company:
    image: sysout1kk/api-company
    ports:
      - "8080:8090"
    environment:
      - spring.cloud.consul.host=consul-agents
      - logging.level.org.springframework.web.client.RestTemplate=DEBUG
      - logging.level.org.springframework.cloud.consul=DEBUG
    depends_on:
      - consul-agents
    deploy:
      replicas: 3

  haproxy:
    image: sysout1kk/haproxy
    ports:
      - "80:80"
    depends_on:
      - api-employee
      - api-company
    deploy:
      replicas: 2

networks:
  default:
    external:
      name: backend
